version: '3.7'
services:
  logging-service:
    container_name: jaeger-tracing-web-redis-demo
    build: 
      context: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/demo
      SPRING_DATASOURCE_USERNAME: demo 
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_REDIS_HOST: redis
    logging:
      driver: fluentd
      options:
        fluentd-address: 172.17.10.105:24224
        tag: web-backend
    ports: 
      - "8000:8080"
    networks:
      - backend
networks:
  backend:
    external:
      name: spring-boot-network
