version: '3.7'
services:
  redis:
    container_name: redis
    image: redis:latest
    expose: 
      - 6379
    logging:
      driver: fluentd
      options:
        fluentd-address: 172.17.10.105:24224
        tag: redis
    networks:
      - storage
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=123456
    volumes:
      - ./psql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pv_postgresql:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 30s
        timeout: 10s
        retries: 5
    networks:
      - storage
volumes:
  pv_postgresql:
networks:
  storage:
    external: 
      name: spring-boot-network
