version: '3.7'
services:
  java-service:
    container_name: spring_boot_demo
    build: 
      context: .
    environment:
      OTEL_TRACES_EXPORTER: otlp 
      OTEL_METRICS_EXPORTER: otlp
      OTEL_EXPORTER_OTLP_ENDPOINT: http://192.168.101.129:4317
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://192.168.101.129:4317
      OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: http://192.168.101.129:4317
      OTEL_EXPORTER_OTLP_TIMEOUT: 1000
      OTEL_RESOURCE_ATTRIBUTES: "service.name=java-demo,service.version=v1.0.0"
      OTEL_PROPAGATORS: "tracecontext,baggage"
      OTEL_INSTRUMENTATION_COMMON_DB_STATEMENT_SANITIZER_ENABLED: "false"
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/demo
      SPRING_DATASOURCE_USERNAME: spring
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_APPLICATION_NAME: dev-mysql-employees
      SPRING_PROFILES_ACTIVE: prod 
      CCH_FLUENTD_PORT: 3003
      CCH_FLUENTD_HOST: 192.168.101.129
    ports: 
      - "8000:8080"
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 5432:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: demo
      MYSQL_USER: spring
      MYSQL_PASSWORD: 123456

volumes:
  db_data: {}
