version: '3.7'
services:
  postgres:
    container_name: postgres_cch
    image: postgres
    restart: always
    ports:
      - "8443:5432"
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=123456
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        #      - postgresql-data:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 30s
        timeout: 10s
        retries: 5


        #volumes:
        #  postgresql-data: